name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: ./Project

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore SharpLibHid.sln
    - name: Build
      run: dotnet build SharpLibHid.sln --no-restore
    - name: Test
      run: dotnet test SharpLibHid.sln --no-build --verbosity normal
    - name: Publish Nuget
      run: dotnet nuget push ./Project/Hid/bin/Release/*.nupkg -k ${NUGET_TOKEN}
      env:
         GITHUB_TOKEN: ${{ secrets.NUGET_TOKEN }}
