name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: ./Project

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore SharpLibHid.sln
    - name: Build debug x86
      run: dotnet build SharpLibHid.sln --no-restore -c Debug /p:Platform=x86
    - name: Build release x86
      run: dotnet build SharpLibHid.sln --no-restore -c Release /p:Platform=x86      
    - name: Build debug x64
      run: dotnet build SharpLibHid.sln --no-restore -c Debug /p:Platform=x64
    - name: Build release x64
      run: dotnet build SharpLibHid.sln --no-restore -c Release /p:Platform=x64       
    - name: Test
      run: dotnet test SharpLibHid.sln --no-build --verbosity normal
    - name: Publish Nuget x86
      run: dotnet nuget push './Hid/bin/x86/Release/Slions.SharpLib.Hid-x86.1.6.0.nupkg' --skip-duplicate -k ${{ secrets.NUGET_CREATE_TOKEN }} --source https://api.nuget.org/v3/index.json 
    - name: Publish Nuget x64
      run: dotnet nuget push './Hid/bin/x64/Release/Slions.SharpLib.Hid-x64.1.6.0.nupkg' --skip-duplicate -k ${{ secrets.NUGET_CREATE_TOKEN }} --source https://api.nuget.org/v3/index.json 

      #env:
      #   NUGET_APIKEY: ${{ secrets.NUGET_TOKEN }}
