name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: ./Project

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore SharpLibHid.sln
    - name: Build debug
      run: dotnet build SharpLibHid.sln --no-restore -c Debug
    - name: Build release
      run: dotnet build SharpLibHid.sln --no-restore -c Release      
    - name: Test
      run: dotnet test SharpLibHid.sln --no-build --verbosity normal
    - name: Publish Nuget
      run: dotnet nuget push './Hid/bin/Release/SharpLibHid.1.5.0.nupkg' --skip-duplicate -k ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json 
      #env:
      #   NUGET_APIKEY: ${{ secrets.NUGET_TOKEN }}
